version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "40753:40753"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 123456789
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: 123456789
    volumes:
      - minio-data:/data
    command: server /data --console-address ":40753"

  myredis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - /root/redis/conf/redis.conf:/etc/redis/redis.conf
      - /root/redis/data:/data
    command: redis-server /etc/redis/redis.conf --appendonly yes

  mysql01:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /root/mysql-conf:/etc/mysql/conf.d
      - /root/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  nacos1:
    image: nacos/nacos-server
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - /root/nacos:/home/nacos/conf
    environment:
      PREFER_HOST_MODE: hostname
      MODE: standalone

  rabbitmq001:
    image: rabbitmq:3.8.16
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /etc/rabbitmq/rabbitmq.conf:/root/rabbitmq.conf
    command: ["rabbitmq-server"]
