version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "44619:44619"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 123456789
      MINIO_ACCESS_KEY: 6FXZj<:eU[RRGDH%xZ4@%=X5Z
      MINIO_SECRET_KEY: 6FXZj<:eU[RRGDH%xZ4@%=X5Z
    volumes:
      - ./minio/data:/data
    restart: always
    command: server --console-address ":44619" /data
  rabbitmq:
    image: rabbitmq:3.8-management  # 注意这里使用 -management 标签
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
  redis:
    image: redis:7.4.2
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data  # 新增：数据持久化目录
    command: redis-server /usr/local/etc/redis/redis.conf
  mysql:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
    volumes_from:
      - mysql-job-dbdata
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: wjh
      MYSQL_PASSWORD: wjh
      MYSQL_ROOT_HOST: "%"
    container_name: mysql  # 可选，可以去掉
    networks:
      - mysql_net
    restart: always  # 可选，可以改为 on-failure
  mysql-job-dbdata:
    image: alpine:3.18.2
    container_name: mysql-job-dbdata
    volumes:
      - /var/lib/mysql
  nginx:
    image: nginx:1.27.0
    container_name: nginx
    ports:
      - "180:180"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always  # 可选，可以改为 on-failure
  nacos:
    image: nacos/nacos-server:v2.1.1
    container_name: nacos
    restart: always
    privileged: true
    environment:
      - MODE= standalone
      - SPRING_DATASOURCE_PLATFORM= mysql
      - MYSQL_SERVICE_HOST= mysql  # 或宿主机的实际 IP（如 192.168.x.x）
      - MYSQL_SERVICE_PORT= 3306
      - MYSQL_SERVICE_USER= root
      - MYSQL_SERVICE_PASSWORD= 123456
      - MYSQL_SERVICE_DB_NAME= nacos
      - TIME_ZONE= Asia/Shanghai
    depends_on:
      - mysql
    networks:
      - mysql_net
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
networks:
  mysql_net:
    driver: bridge