version: '3.8'

services:
  article:
    build: 
     dockerfile: article.service
    ports:
      - "8085:8085"
    networks:
      - mynetwork  
  gateway:
    build: 
     dockerfile: gateway.service
    ports:
      - "10010:10010"
    networks:
      - mynetwork  
  question:
    build: 
     dockerfile: question.service
    ports:
      - "8082:8082"
    networks:
      - mynetwork
  user:
    build: 
     dockerfile: user.service
    ports:
      - "8083:8083"
    networks:
      - mynetwork    
  run:
    build: 
     dockerfile: run.service
    ports:
      - "8086:8086"
    networks:
      - mynetwork   
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "40753:40753"
    networks:
      - mynetwork
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 123456789
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: 123456789
    volumes:
      - minio-data:/data
    command: server /data --console-address ":40753"

  myredis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - /root/redis/conf/redis.conf:/etc/redis/redis.conf
      - /root/redis/data:/data
    command: redis-server /etc/redis/redis.conf --appendonly yes
    networks:
      - mynetwork

  mysql01:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - /root/mysql-conf:/etc/mysql/conf.d
      - /root/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - mynetwork

  nacos1:
    image: nacos/nacos-server
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - /root/nacos:/home/nacos/conf
    environment:
      PREFER_HOST_MODE: hostname
      MODE: standalone
    networks:
      - mynetwork

  rabbitmq001:
    image: rabbitmq:3.8.16
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /etc/rabbitmq/rabbitmq.conf:/root/rabbitmq.conf
    command: ["rabbitmq-server"]
    networks:
      - mynetwork
volumes:
  minio-data:

networks:
  mynetwork:
    driver: bridge
